version: "3"

services:
  authDB:
    image: postgres:15.3
    container_name: auth-db
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=better_auth
    volumes:
      - ./postgres:/var/lib/postgresql/data
